#!/usr/bin/env python
"""
Sphinx configurtion for the Ops of Iris.
"""
# It's a customized, comment-stripped version of the conf.py generated by sphinx-quickstart. For further info look in to the comments of an unstripped conf.py generated by the same.

# This file is shouldn't be executed manually, for more info learn about sphinx.

import sys
import os

project_root = os.path.abspath("../")

sys.path.insert(0, '%s/examples' % project_root)
sys.path.insert(0, project_root)

# imports
from eccontrib import sphinxdoc

# General config

extensions = ['eccontrib.sphinxdoc']
templates_path = ['_templates']
source_suffix = '.rst'
#source_encoding = 'utf-8-sig'
master_doc = 'index'

# General information about the project.
project = u'eccontrib-sphinxdoc'
copyright = u'2015, Laufire Technologies'
version = sphinxdoc.__version__
release = sphinxdoc.__version__

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build']

today_fmt = '%Y%m%d'
add_module_names = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

html_theme = 'sphinx_rtd_theme'
# html_title = None # "<project> v<release> documentation".
# html_logo = None
# html_favicon = None
# html_static_path = ['_static']
html_last_updated_fmt = '%Y%m%d'
htmlhelp_basename = 'ecdoc'
